### ISSUE TITLE
Building Steps Not Clear

### ISSUE THREAD

**Issue by Positron010** [ZanSara/ebisu-flashcards#2]
Please provide clear steps to build the app for beginners. I am extremely interested in this project, and will be grateful if you could do that. Thanks!

**Comment by ZanSara** [comment]
Hello,

Actually the project is far from complete (it's no more than my pet project TBH), so if you are not very familiar with Python I don't recommend you trying. It just doesn't work yet, that's why I didn't bother to add instructions on how to build it.
If you're interested anyway or want to fork it, here is a quick idea of the process (no guarantees I'll work out) assuming you're on Linux:
- Make sure you have Python3.7+
- Clone the project
- Install it in a virtualenv (it has a `setup.py`, so `pip install . ` should work
- Type `ebisu` and it should spin up the server. 

Then visit http://127.0.0.1:3501

To have it fully working you'll need a running MongoDB instance too. Just install it on your system and make sure it's running when you start the server.

I think that's it. Feel free to ask again but, as I said, if you want to work on this I recommend you fork it and play with it. Otherwise come back in a few months and hopefully you'll find a working codebase 😄  

Best of luck!

(Please close the issue as soon as you think I answered your question)

**Comment by Positron010** [comment]
Hi, and thank you for your fast and helpful reply, I am really grateful. 

When I run `pip install .` I get this error:

`ERROR: For req: ebisu-flashcards==0.0.1. Invalid script entry point: <ExportEntry ebisu = ebisu_flashcards.run:None []> - A callable suffix is required. Cf https://packaging.python.org/specifications/entry-points/#use-for-scripts for more information.`


Thank you again!

**Comment by Positron010** [comment]
OK! After a lot of trial and error, and visiting StackOverflow a lot of times, I managed to run the app! Now I'm faced by a login _or_ signup page. How can I proceed @ZanSara ?

Thanks!

**Comment by ZanSara** [comment]
Hello,

Again, the application is not complete: it just doesn't work yet. 

If you have MongoDB running, you might be able to do the registration (like on any other website) and then login, but it might be broken. I don't know if the version here on GitHub works or not. My local copy surely doesn't.

So don't expect it to just work...

If you are not able to read the code and fix the bugs on your own, please wait until I release a working version. No point wasting time now. If instead you're happy to debug it yourself, please fork the repository and modify it as you wish.

**Comment by Positron010** [comment]
Hi,
Got it! Thanks for taking the time to reply to me @ZanSara . Really appreciated!
BTW, is there a place to support or collaborate with you? Please let me know!
Thanks again.

**Comment by ZanSara** [comment]
For now there is not much you can do to help, but thanks for the offer! 

Hopefully in a few months the whole project will be in a more usable state. I'll do my best to remember to let you know.
